### ISSUE TITLE
stuck on creating library

### ISSUE THREAD

**Issue by muneebhussain15** [stewartmcgown/drivestream#2]
I am stuck in this part

A small summary of what I have done

fresh clean install ubuntu 16.04 and windows 10

followed your steps
```

Create credentials for Google Drive using the wizard
Add those credentials to a file in the project root called 'credentials.js'
export const API_KEY = "YOUR_API_KEY"
export const CLIENT_ID = "YOUR_CLIENT_ID"
Run the project using npm run dev
```
It asks me to sign in which I do

I can also create library

and my google drive folders are seen

here as you can see I can see my folders

![image](https://user-images.githubusercontent.com/15520829/54882942-4a8ccd00-4e81-11e9-847f-428863a89775.png)

however after clicking create I am forever stuck in the creating phase and the white box that gives the option to update or refresh metadata never shows up

It works fine on your demo site.

Can you please advise on what I could be possibly doing wrong?

**Comment by stewartmcgown** [comment]
What error message do you get in the console?

**Comment by muneebhussain15** [comment]
I dont see any error messages

![image](https://user-images.githubusercontent.com/15520829/54888387-8d20ca80-4ebe-11e9-8c4e-d0fa7b51a7eb.png)

![image](https://user-images.githubusercontent.com/15520829/54888408-b5102e00-4ebe-11e9-8652-5441c93f3f3d.png)



this is all I see on ubuntu 16.04 and this is what I see on windows 10

both have the same issue


![image](https://user-images.githubusercontent.com/15520829/54888428-dcff9180-4ebe-11e9-8790-37ae491b2686.png)

**Comment by stewartmcgown** [comment]
Errors from chrome console needed, that is just a static file server. Open
up devtools and show me that log

**Comment by muneebhussain15** [comment]
got it to work

sorry 
basically got an error that google sheets api was not used in this project or is disabled. Enable by visiting the link

and was given the link

enabling fix it.

Thank you so much and thanks for handling the brain fart 👍
