### ISSUE TITLE
Google issue

### ISSUE THREAD

**Issue by Kongledyret** [stewartmcgown/drivestream#5]
Hi! 
I'm trying to create the credentials.js file with ID and API, but
getting: Error: invalid_request

Storagerelay URI is not allowed for 'NATIVE' client type.

Any idea?

**Comment by stewartmcgown** [comment]
Did you follow instructions to rename File? Also it's .JSON not .JS

**Comment by Sc4nd4l** [comment]
Hi, 
Yes. Testing with the https://developers.google.com/drive/api/v3/quickstart/js works fine.

**Comment by Kongledyret** [comment]
Hi,
Yes. Testing with the https://developers.google.com/drive/api/v3/quickstart/js works fine.

**Comment by Kongledyret** [comment]
Any idea?

**Comment by stewartmcgown** [comment]
I'm afraid not. I'm never really sure what these kind of specific issues
could be caused by

**Comment by Kongledyret** [comment]
Ok. Is it possible to see a screen on how your keys are configured in case of bad creation ?
